### ISSUE TITLE
Avoid cwltool dependency

### ISSUE THREAD

**Issue by stain** [common-workflow-language/cwljava#11]
I tried building with `mvn clean install` and I got:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running CWLClientTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "cwltool" (in directory "."): error=2, No such file or directory)
    at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:205)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "cwltool" (in directory "."): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
    at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
    at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
    at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
    ... 1 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 7 more
org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "cwltool" (in directory "."): error=2, No such file or directory)
    at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:205)
    at java.lang.Thread.run(Thread.java:745)
```

Why would I need to have `cwltool` installed (the Python implementation) if I am building the Java implementation? Surely the two should be independent..?

**Comment by stain** [comment]
Might be related to #6  - I must admit I am still a bit confused here.. :)

**Comment by pgrosu** [comment]
Hi Stain,

There were initially two versions.  What you are running is what is now under:

https://github.com/common-workflow-language/cwlavro

We will be updating what is under the following link to be the main version, which does not have any dependency on any other tool:

https://github.com/common-workflow-language/cwljava/tree/develop/WIP/paul

Hopefully within a week we'll have a PR to work from to tweak, and you would welcome to join the tests/tweaks.

Sorry about the confusion.

Paul

**Comment by stain** [comment]
OK, I think I'll have a look at cwlavro then.. I must admit I don't understand https://github.com/common-workflow-language/cwljava/tree/develop/WIP/paul as it's not structured as a Maven project.. :)

**Comment by pgrosu** [comment]
We're working towards that direction :)  Kyle (@kellrott) made a nice PR (https://github.com/common-workflow-language/cwljava/pull/5) which I'll merge soon, but there is a lot of code update and simplification I am currently performing to have it Draft-3 compliant.  Very soon and sorry for the inconvenience.  I will ping you again once we're ready.

Thanks,
Paul
