### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jdidion** [common-workflow-language/cwljava#40]
There are 6 workflow tests that fail with the same exception. Looks to have something to do with parsing the outputSource that refers to a step output.

* [] https://github.com/common-workflow-language/cwl-v1.2/blob/main/tests/count-lines10-wf.cwl
* [] https://github.com/common-workflow-language/cwl-v1.2/blob/main/tests/count-lines14-wf.cwl
* [] https://github.com/common-workflow-language/cwl-v1.2/blob/main/tests/count-lines15-wf.cwl
* [] https://github.com/common-workflow-language/cwl-v1.2/blob/main/tests/count-lines16-wf.cwl
* [] https://github.com/common-workflow-language/cwl-v1.2/blob/main/tests/count-lines17-wf.cwl
* [] https://github.com/common-workflow-language/cwl-v1.2/blob/main/tests/count-lines18-wf.cwl

```
java.lang.NullPointerException:
[info]   at org.w3id.cwl.cwl1_2.utils.LoadingOptions.expandUrl(LoadingOptions.java:94)
[info]   at org.w3id.cwl.cwl1_2.utils.UriLoader.expandUrl(UriLoader.java:26)
[info]   at org.w3id.cwl.cwl1_2.utils.UriLoader.load(UriLoader.java:48)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.load(Loader.java:16)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.loadField(Loader.java:99)
[info]   at org.w3id.cwl.cwl1_2.WorkflowOutputParameterImpl.<init>(WorkflowOutputParameterImpl.java:350)
[info]   at sun.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at org.w3id.cwl.cwl1_2.utils.RecordLoader.load(RecordLoader.java:23)
[info]   at org.w3id.cwl.cwl1_2.utils.RecordLoader.load(RecordLoader.java:6)
[info]   at org.w3id.cwl.cwl1_2.utils.UnionLoader.load(UnionLoader.java:26)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.load(Loader.java:16)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.loadField(Loader.java:99)
[info]   at org.w3id.cwl.cwl1_2.utils.ArrayLoader.load(ArrayLoader.java:27)
[info]   at org.w3id.cwl.cwl1_2.utils.ArrayLoader.load(ArrayLoader.java:6)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.load(Loader.java:16)
[info]   at org.w3id.cwl.cwl1_2.utils.IdMapLoader.load(IdMapLoader.java:51)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.load(Loader.java:16)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.loadField(Loader.java:99)
[info]   at org.w3id.cwl.cwl1_2.WorkflowImpl.<init>(WorkflowImpl.java:348)
[info]   at sun.reflect.GeneratedConstructorAccessor51.newInstance(Unknown Source)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at org.w3id.cwl.cwl1_2.utils.RecordLoader.load(RecordLoader.java:23)
[info]   at org.w3id.cwl.cwl1_2.utils.RecordLoader.load(RecordLoader.java:6)
[info]   at org.w3id.cwl.cwl1_2.utils.UnionLoader.load(UnionLoader.java:26)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.load(Loader.java:16)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.loadField(Loader.java:99)
[info]   at org.w3id.cwl.cwl1_2.WorkflowStepImpl.<init>(WorkflowStepImpl.java:401)
[info]   at sun.reflect.GeneratedConstructorAccessor50.newInstance(Unknown Source)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at org.w3id.cwl.cwl1_2.utils.RecordLoader.load(RecordLoader.java:23)
[info]   at org.w3id.cwl.cwl1_2.utils.RecordLoader.load(RecordLoader.java:6)
[info]   at org.w3id.cwl.cwl1_2.utils.UnionLoader.load(UnionLoader.java:26)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.load(Loader.java:16)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.loadField(Loader.java:99)
[info]   at org.w3id.cwl.cwl1_2.utils.ArrayLoader.load(ArrayLoader.java:27)
[info]   at org.w3id.cwl.cwl1_2.utils.ArrayLoader.load(ArrayLoader.java:6)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.load(Loader.java:16)
[info]   at org.w3id.cwl.cwl1_2.utils.IdMapLoader.load(IdMapLoader.java:51)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.load(Loader.java:16)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.loadField(Loader.java:99)
[info]   at org.w3id.cwl.cwl1_2.WorkflowImpl.<init>(WorkflowImpl.java:438)
[info]   at sun.reflect.GeneratedConstructorAccessor51.newInstance(Unknown Source)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at org.w3id.cwl.cwl1_2.utils.RecordLoader.load(RecordLoader.java:23)
[info]   at org.w3id.cwl.cwl1_2.utils.RecordLoader.load(RecordLoader.java:6)
[info]   at org.w3id.cwl.cwl1_2.utils.UnionLoader.load(UnionLoader.java:26)
[info]   at org.w3id.cwl.cwl1_2.utils.Loader.documentLoad(Loader.java:41)
[info]   at org.w3id.cwl.cwl1_2.utils.RootLoader.loadDocument(RootLoader.java:18)
[info]   at org.w3id.cwl.cwl1_2.utils.RootLoader.loadDocument(RootLoader.java:86)
[info]   at org.w3id.cwl.cwl1_2.utils.RootLoader.loadDocument(RootLoader.java:45)
```

**Comment by mr-c** [comment]
This has been fixed for a while
